### PR TITLE
Support for Gemini tool calling (plus general fixes)

### PR DESCRIPTION
**Pull request by marklysze**
## Why are these changes needed?

The Gemini class doesn't currently support tool calling.

This PR adds tool calling.

Additional updates:
- Removal of role alternation, this no longer appears necessary
- Image input corrected for non-Vertex AI
- Costs updated

**NOTE:** This hasn't been tested with Vertex AI authentication, if someone can test it that would be good. Please try the client [test files in my repo](https://github.com/marklysze/AutoGenClientTesting).

## Related issue number

[Noted in Discord issue](https://discord.com/channels/1153072414184452236/1290748511062589543)

## Checks

- [ ] I've included any doc changes needed for https://ag2ai.github.io/autogen/. See https://ag2ai.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by qingyun-wu** [comment]
@marklysze there are conflicts. Could you fix the conflicts in this PR or draft a new PR? Thank you!

**Comment by luxzoli** [comment]
@marklysze I have found a few minor issues when testing it with VertexAI using some of my own tests. I would still have to go through your tests. Should I prepare a PR to your branch for the suggested (minor) changes to support VertexAI as well?

**Comment by marklysze** [comment]
> @marklysze I have found a few minor issues when testing it with VertexAI using some of my own tests. I would still have to go through your tests. Should I prepare a PR to your branch for the suggested (minor) changes to support VertexAI as well?

Thanks for that @luxzoli! It would be great if you could work on this branch.

Let me update the branch in line with main now.

**Comment by marklysze** [comment]
@luxzoli, would you be on Discord as well? If so, can you let me know your Discord ID? If you want to message me on there, my Discord ID is `msze_`

**Comment by marklysze** [comment]
Thanks @luxzoli, branch is updated, let me know how you go :)

**Review by qingyun-wu — APPROVED** [review]

**Comment by qingyun-wu** [comment]
@marklysze could you fix the conflicts? Thank you!

**Comment by marklysze** [comment]
> @marklysze I have found a few minor issues when testing it with VertexAI using some of my own tests. I would still have to go through your tests. Should I prepare a PR to your branch for the suggested (minor) changes to support VertexAI as well?

Hi @luxzoli, I'll merge this one as we're due for a release, if there are VertexAI changes or other fixes, can you please create a new PR?

**Comment by luxzoli** [comment]
> > @marklysze I have found a few minor issues when testing it with VertexAI using some of my own tests. I would still have to go through your tests. Should I prepare a PR to your branch for the suggested (minor) changes to support VertexAI as well?
> 
> Hi @luxzoli, I'll merge this one as we're due for a release, if there are VertexAI changes or other fixes, can you please create a new PR?

Sure! Nevertheless, yesterday I have tested the function calling again with VertexAI, and my original fix is not needed anymore 🙂
For other things I will create a new PR then

**Pull request merged**
