### PR TITLE
Improve agent telemetry tracking in GraphRAG for trip planning

### PR DESCRIPTION
**Pull request by donbr**
This PR provides a robust example on the value of Telemetry data to improve visibility into Swarm behavior for complex sceanrios:  `agentchat_swarm_graphrag_telemetry_trip_planner.ipynb`.

The notebook walks through the process of setting up telemetry using Arize Phoenix, improving visibility to the swarm's decision-making process throughout trip planning. This includes:
- improved fine-grained telemetry information to better understand node selection behavior.
- Logging time taken for various stages of agent processing.
- (Future) Adding real-time performance monitoring visualizations.

These changes address gaps in observability that were experienced while reviewing the [agentchat_swarm_graphrag_trip_planner.ipynb](https://github.com/ag2ai/ag2/blob/main/notebook/agentchat_swarm_graphrag_trip_planner.ipynb) notebook.

## Checks

- [x] I've included any doc changes needed for https://ag2ai.github.io/ag2/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by marklysze** [comment]
@donbr, this is very cool, thanks for creating it.

Does the telemetry capture all OpenAI messages, tokens, and costs? The reason I ask is some of the GraphRAG SDK OpenAI API calls are done deep in the SDK and we don't have visibility of them.

**Comment by donbr** [comment]
@marklysze - we can run a test and validate the results.  How deep the calls are within the SDK shouldn't matter - this is specifically capturing the calls to the LLM.

**Comment by marklysze** [comment]
> @marklysze - we can run a test and validate the results. How deep the calls are within the SDK shouldn't matter - this is specifically capturing the calls to the LLM.

Great, that gives good visibility...

**Comment by donbr** [comment]
Sample Trace for entity and relationship extraction:

## SYSTEM:

You are a top-tier assistant with the goal of extracting entities and relations from text for a graph database, using the provided ontology.
Use only the provided entities, relation, and attributes in the ontology.
Maintain Entity Consistency: When extracting entities, it's vital to ensure consistency. If an entity, such as "John Doe", is mentioned multiple times in the text but is referred to by different names or pronouns (e.g., "Joe", "he"), always use the most complete identifier for that entity throughout the knowledge graph. In this example, use "John Doe" as the entity ID. Remember, the knowledge graph should be coherent and easily understandable, so maintaining consistency in entity references is crucial.

Maintain format consistency: Ensure that the format of the extracted data is consistent with the provided ontology and context, to facilitate queries. For example, dates should always be in the format "YYYY-MM-DD", names should be consistently spaced, and so on.
Do not use any other entities, relations, or attributes that are not provided in the ontology.

Do not include any explanations or apologies in your responses.
Do not respond to any questions that might ask anything else than data extraction.

Your response should be in JSON format and should follow the schema provided below.

Make sure the output JSON is returned inline and with no spaces, so to save in the output tokens count.

Schema:
```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "Graph Schema",
  "required": ["entities", "relations"],
  "properties": {
    "entities": {
      "type": "array",
      "title": "The entities Schema",
      "items": {
        "type": "object",
        "title": "A Schema",
        "required": ["label", "attributes"],
        "properties": {
          "label": {
            "type": "string",
            "title": "The label Schema",
            "format": "titlecase"
          },
          "attributes": {
            "type": "object",
            "title": "The attributes Schema"
          }
        }
      }
    },
    "relations": {
      "type": "array",
      "title": "The relations Schema",
      "items": {
        "type": "object",
        "title": "A Schema",
        "required": ["label", "source", "target"],
        "properties": {
          "label": {
            "type": "string",
            "title": "The label Schema",
            "format": "uppercase"
          },
          "source": {
            "type": "object",
            "title": "The source Schema",
            "required": ["label", "attributes"],
            "properties": {
              "label": {
                "type": "string",
                "format": "titlecase",
                "title": "The label Schema"
              },
              "attributes": {
                "type": "object",
                "title": "The attributes Schema"
              }
            }
          },
          "target": {
            "type": "object",
            "title": "The target Schema",
            "required": ["label", "attributes"],
            "properties": {
              "label": {
                "type": "string",
                "format": "titlecase",
                "title": "The label Schema"
              },
              "attributes": {
                "type": "object",
                "title": "The attributes Schema"
              }
            }
          },
          "attributes": {
            "type": "object",
            "title": "The attributes Schema"
          }
        }
      }
    }
  }
}
```

Output example:
```{"entities":[{"label":"Person","attributes":{"name":"John Doe","age":30}},{"label":"Movie","attributes":{"title":"Inception","releaseYear":2010}}],"relations":[{"label":"ACTED_IN","source":{"label":"Person","attributes":{"name":"JohnDoe"}},"target":{"label":"Movie","attributes":{"title":"Inception"}},"attributes":{"role":"Cobb"}}]}```

Ontology:
{'entities': [{'label': 'Country', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}], 'description': ''}, {'label': 'City', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}, {'name': 'weather', 'type': 'string', 'unique': False, 'required': False}, {'name': 'population', 'type': 'number', 'unique': False, 'required': False}], 'description': ''}, {'label': 'Restaurant', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}, {'name': 'description', 'type': 'string', 'unique': False, 'required': False}, {'name': 'rating', 'type': 'number', 'unique': False, 'required': False}, {'name': 'food_type', 'type': 'string', 'unique': False, 'required': False}], 'description': ''}, {'label': 'Attraction', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}, {'name': 'description', 'type': 'string', 'unique': False, 'required': False}, {'name': 'type', 'type': 'string', 'unique': False, 'required': False}], 'description': ''}], 'relations': [{'label': 'IN_COUNTRY', 'source': {'label': 'City'}, 'target': {'label': 'Country'}, 'attributes': []}, {'label': 'IN_CITY', 'source': {'label': 'Restaurant'}, 'target': {'label': 'City'}, 'attributes': []}, {'label': 'IN_CITY', 'source': {'label': 'Attraction'}, 'target': {'label': 'City'}, 'attributes': []}]}


## USER:

You are tasked with extracting entities and relations from the text below, using the ontology provided.

**Output Format:**

- Provide the extracted data as a JSON object with two keys: `"entities"` and `"relations"`.

- **Entities**: Represent entities and concepts. Each entity should have a `"label"` and `"attributes"` field.

- **Relations**: Represent relations between entities or concepts. Each relation should have a `"label"`, `"source"`, `"target"`, and `"attributes"` field.

**Guidelines:**
- **Extract all entities and relations**: Capture all entities and relations mentioned in the text.

- **Use Only the Provided Ontology**: Utilize only the types of entities, relations, and attributes defined in the ontology.

- **Assign IDs Where Required**: Assign textual IDs to entities and relations as specified.

- **Avoid Duplicates**: Ensure each entity and relation is unique; do not include duplicates.

- **Formatting**:
  - Do not include any introduction or explanation in the response, only the JSON.
  
  - Use double quotes for all string values.

  - Properly escape any special characters.

  - Dates should be in the format `"YYYY-MM-DD"`.

  - Correct any spacing or formatting issues in text fields as necessary.

- **Precision**: Be concise and precise in your extraction.

- **Token Limit**: Ensure your response does not exceed **8192 tokens**.

**User Instructions**:



**Ontology**:
{'entities': [{'label': 'Country', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}], 'description': ''}, {'label': 'City', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}, {'name': 'weather', 'type': 'string', 'unique': False, 'required': False}, {'name': 'population', 'type': 'number', 'unique': False, 'required': False}], 'description': ''}, {'label': 'Restaurant', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}, {'name': 'description', 'type': 'string', 'unique': False, 'required': False}, {'name': 'rating', 'type': 'number', 'unique': False, 'required': False}, {'name': 'food_type', 'type': 'string', 'unique': False, 'required': False}], 'description': ''}, {'label': 'Attraction', 'attributes': [{'name': 'name', 'type': 'string', 'unique': True, 'required': True}, {'name': 'description', 'type': 'string', 'unique': False, 'required': False}, {'name': 'type', 'type': 'string', 'unique': False, 'required': False}], 'description': ''}], 'relations': [{'label': 'IN_COUNTRY', 'source': {'label': 'City'}, 'target': {'label': 'Country'}, 'attributes': []}, {'label': 'IN_CITY', 'source': {'label': 'Restaurant'}, 'target': {'label': 'City'}, 'attributes': []}, {'label': 'IN_CITY', 'source': {'label': 'Attraction'}, 'target': {'label': 'City'}, 'attributes': []}]}

**Raw Text**:
[
  {
    "id": 1,
    "name": "Rome",
    "country": "Italy",
    "population": 2800000,
    "weather": "Mediterranean"
  },
  {
    "id": 2,
    "name": "Milan",
    "country": "Italy",
    "population": 1370000,
    "weather": "Humid subtropical"
  },
  {
    "id": 3,
    "name": "Naples",
    "country": "Italy",
    "population": 967000,
    "weather": "Mediterranean"
  },
  {
    "id": 4,
    "name": "Turin",
    "country": "Italy",
    "population": 875000,
    "weather": "Humid subtropical"
  },
  {
    "id": 5,
    "name": "Palermo",
    "country": "Italy",
    "population": 673000,
    "weather": "Mediterranean"
  },
  {
    "id": 6,
    "name": "Genoa",
    "country": "Italy",
    "population": 580000,
    "weather": "Mediterranean"
  },
  {
    "id": 7,
    "name": "Bologna",
    "country": "Italy",
    "population": 390000,
    "weather": "Humid subtropical"
  },
  {
    "id": 8,
    "name": "Florence",
    "country": "Italy",
    "population": 383000,
    "weather": "Temperate"
  },
  {
    "id": 9,
    "name": "Venice",
    "country": "Italy",
    "population": 260000,
    "weather": "Humid subtropical"
  },
  {
    "id": 10,
    "name": "Verona",
    "country": "Italy",
    "population": 258000,
    "weather": "Humid subtropical"
  }
]

## ASSISTANT:

{"entities":[{"label":"Country","attributes":{"name":"Italy"}},{"label":"City","attributes":{"name":"Rome","population":2800000,"weather":"Mediterranean"}},{"label":"City","attributes":{"name":"Milan","population":1370000,"weather":"Humid subtropical"}},{"label":"City","attributes":{"name":"Naples","population":967000,"weather":"Mediterranean"}},{"label":"City","attributes":{"name":"Turin","population":875000,"weather":"Humid subtropical"}},{"label":"City","attributes":{"name":"Palermo","population":673000,"weather":"Mediterranean"}},{"label":"City","attributes":{"name":"Genoa","population":580000,"weather":"Mediterranean"}},{"label":"City","attributes":{"name":"Bologna","population":390000,"weather":"Humid subtropical"}},{"label":"City","attributes":{"name":"Florence","population":383000,"weather":"Temperate"}},{"label":"City","attributes":{"name":"Venice","population":260000,"weather":"Humid subtropical"}},{"label":"City","attributes":{"name":"Verona","population":258000,"weather":"Humid subtropical"}}],"relations":[{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Rome"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Milan"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Naples"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Turin"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Palermo"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Genoa"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Bologna"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Florence"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Venice"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}},{"label":"IN_COUNTRY","source":{"label":"City","attributes":{"name":"Verona"}},"target":{"label":"Country","attributes":{"name":"Italy"}},"attributes":{}}]}

**Pull request closed without merging**
