### PR TITLE
fix base_url not work in groq

### PR DESCRIPTION
**Pull request by simplaj**
## Why are these changes needed?

The base_url functionality in Groq was not working correctly in AutoGen version 0.4.1. This PR addresses the issue by fixing the logic for handling the base_url parameter, ensuring it functions as expected.

## Checks

- [ ] I've included any doc changes needed for https://ag2ai.github.io/ag2/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by marklysze** [comment]
@simplaj, thanks so much for adding support for `base_url`. I've tested your changes and they look good!

Can I have your Discord ID and email so that we can acknowledge your contribution, and also have you sign CLA properly! I'm `msze_` on Discord if you wanted to message me, or you can catch me on the [AG2 Discord](https://discord.gg/pAbnFJrkgZ) server.

**Comment by simplaj** [comment]
Thank you for testing and confirming the changes! I appreciate your acknowledgment and would be happy to provide my Discord ID and email for proper CLA signing. My Discord ID is tianzhihua, and my email is zhihuatean@gmail.com. I'll also message you on Discord shortly to stay in touch.

Thanks again for your support!

**Review by marklysze — APPROVED** [review]
Looks good, thanks!

**Comment by marklysze** [comment]
Passed tests, except OpenAI which can't run as not in repo. Won't affect OpenAI as Groq specific. Merging.

**Pull request merged**
