### PR TITLE
limit coding to python and shell in autobuild

### PR DESCRIPTION
**Pull request by szwang-seedtech**
## Why are these changes needed?

 
The current autobuild only restricts coding to Python and Shell within the CODING_AND_TASK_SKILL_INSTRUCTION section. However, this does not completely prevent the LLM from generating agents in other programming languages, such as Java_Expert or C_Expert.

Adding restrictions in the AGENT_NAME_PROMPT can address this issue.

## Checks

- [ ] I've included any doc changes needed for https://ag2ai.github.io/ag2/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by singulaai — APPROVED** [review]
LGTM

**Review by Hk669 — APPROVED** [review]
lgtm.

**Comment by sonichi** [comment]
@szwang-seedtech thanks for the contribution. Could you please share your discord handle so that we can follow up there and also make it easier to acknowledge your contribution?

**Comment by szwang-seedtech** [comment]
@sonichi My discord handle is sager3890

**Pull request merged**
