### PR TITLE
Update retrieve_user_proxy_agent.py

### LINKED ISSUE #51: [Bug]: ValueError with RetrieveUserProxyAgent's default client
### Describe the bug

In RetrieveUserProxyAgent, when using a VectorDB instance for the `vector_db` argument, the client should be the one that the VectorDB instance uses.
https://github.com/ag2ai/ag2/blob/main/autogen/agentchat/contrib/retrieve_user_proxy_agent.py#L264

### Steps to reproduce

- Create a new chromadb client: 
    ```
    import chromadb
    from chromadb.config import Settings
    client = chromadb.PersistentClient(path="/path/to/documents", settings=Settings(anonymized_telemetry=False)
    ```
- Try to use this client in a RetrieveUserProxyAgent:
     ```
     from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent
     from autogen.agentchat.contrib.vectordb.chromadb import ChromaVectorDB
     from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
     agent = RetrieveUserProxyAgent(
         ...,
         retrieve_config={
             ...,
             "vector_db": ChromaVectorDB(
                 client=client,
                 embedding_function=SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
             ),
            ...
      )
-  Trying to use this agent gives:
     `ValueError: An instance of Chroma already exists for ephemeral with different settings:`
     ```
     ...site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py#line=265), in RetrieveUserProxyAgent.__init__(self, name, human_input_mode, is_termination_msg, retrieve_config, **kwargs)
         264 self._client = self._retrieve_config.get("client", None)
         265 if self._client is None:
     --> 266     self._client = chromadb.Client()
     ....
     ```

### Model Used

_No response_

### Expected Behavior

Not to throw an error and use the provided client.

### Screenshots and logs

_No response_

### Additional Information

Maybe related: https://github.com/microsoft/autogen/issues/2829

### PR DESCRIPTION
**Pull request by lazToum**
## Why are these changes needed?
An additional check in `_vector_db` is added before generating a default client in `RetrieveUserProxyAgent`

## Related issue number

Closes #51
## Checks

- [ ] I've included any doc changes needed for https://ag2ai.github.io/ag2/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by Hk669 — APPROVED** [review]
looks good to me. Thanks @lazToum

**Comment by qingyun-wu** [comment]
@lazToum, in order to run the "OpenAI4ContribTests" the code needs to come from a branch in ag2ai, could you create a branch? Let me know if you don't have access. Also could you let me know your discord id or email?

**Comment by lazToum** [comment]
> @lazToum, in order to run the "OpenAI4ContribTests" the code needs to come from a branch in ag2ai, could you create a branch? Let me know if you don't have access. Also could you let me know your discord id or email?

Sure,
I tried, but it seems I don't have access :(  I got `ERROR: Permission to ag2ai/ag2.git denied`
I'm laztoum @ discord.

**Comment by lazToum** [comment]
Closing in favor of  https://github.com/ag2ai/ag2/pull/118

**Pull request closed without merging**
