### PR TITLE
Docs: Add OpenLIT to Agent Observability doc along with notebook

### PR DESCRIPTION
**Pull request by amanagarwal042**
## Why are these changes needed?

Hi Team, I am one of the maintainers of [OpenLIT](https://github.com/openlit/openlit) and we support Obserability for Agents built using AG2, It is all OpenTelemetry-native so the traces and metrics can be sent to any platfrom like [Grafana](https://grafana.com/docs/grafana-cloud/monitor-applications/ai-observability/introduction/) or any [OSS OTel tools](https://opentelemetry.io/blog/2024/llm-observability/)

Figured the mention here might be useful for developers using AG2 hence adding the reference in Agent Observabiliy documentation page along with a notebook

## Checks

- [x] I've included any doc changes needed for https://ag2ai.github.io/ag2/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by mcam10** [comment]
> @qingyun-wu Hey saw you triggered the run again hence tagging you, It seems to be failing some tests but I can seem to figure out why as it failing for not finidng `/docs/notebooks/agentops_openlit`. I see a similar path used for agentops notebook hence used the same but lemme know if II should be using something else.

@patcher9... 
Inside of the pipeline for docs.. the error is reporting:

> Exhaustive list of all broken links found:
>   - Broken link on source page path = /ag2/docs/topics/llm-observability:
>      -> linking to `/ag2/docs/notebooks/agentchat_openlit
 
 I can see this locally when trying to run `npm run build` inside of `ag2/website`.. 
 
 I used the github url [Tutorial Notebook](https://github.com/patcher9/ag2/blob/main/notebook/agentchat_openlit.ipynb)

**Review by mcam10 — COMMENTED** [review]
have you tried running those pre commit hooks locally? 

also in the docs pipeline  
the `npm run build` step fails because of broken links.. 

think you gotta use the github url to the actual notebook  [View Notebook](https://github.com/patcher9/ag2/blob/main/notebook/agentchat_openlit.ipynb)

**Comment by mcam10** [comment]
> > agentchat_openlit.ipynb: front matter missing from notebook metadata in the pipeline output as well.
> 
> Ah yeah had left it for last ad then completely forgot, Added it now
> 
> > think you gotta use the github url to the actual notebook [View Notebook](https://github.com/patcher9/ag2/blob/main/notebook/agentchat_openlit.ipynb)
> 
> So instead of `- [Tutorial Notebook](/docs/notebooks/agentchat_openlit)` I should be doing - [Tutorial Notebook](https://github.com/patcher9/ag2/blob/main/notebook/agentchat_openlit.ipynb), That correct?

@patcher9 yep.

**Comment by mcam10** [comment]
> Also `/docs/notebooks/agentchat_agentops` this is whatt is being used in Agentops in the same file whic is why I intially used what I had earlier. Lemme know whatever works.

yeah thats a good point.. @olaoluwasalami @Hk669 @rudyalways @sonichi  @qingyun-wu  @marklysze   -- do we have a preference on how notebooks should be referenced ? Like full github URL vs the  `/docs/..` strategy.. (from what ive seen this just goes to a 404 -- which makes sense)..

In @patcher9's case  -- post merge there will need to be another PR to reference this repository instead..

Another example -  https://github.com/ag2ai/ag2/blob/main/website/docs/topics/retrieval_augmentation.md 
RAG: Group Chat with Retrieval Augmented Generation (with 5 group member agents and 1 manager agent) -> goes to 404 
vs.
Chat with OpenAI Assistant with Retrieval Augmentation -> goes to notebook file (full github url)

Also, those respective pipelines should've failed too if those links are "broken" 🤔??

Lastly, Im curious if @patcher9's build will pass now though? How do we trigger another run?

**Comment by Hk669** [comment]
@patcher9 thanks for adding the OpenLIT, to make it more usable and handy to the community, can you make the notebook more comprehensive about the API keys( if required to access the platform ). 

please take this as a reference: https://ag2ai.github.io/ag2/docs/notebooks/agentchat_agentops

**Comment by Hk669** [comment]
> have you tried running those [pre commit hooks locally ](https://ag2ai.github.io/ag2/docs/contributor-guide/pre-commit)?
> 
> in the docs pipeline the `npm run build` step fails because of broken links..
> 
> think you gotta use the github url to the actual notebook [View Notebook](https://github.com/patcher9/ag2/blob/main/notebook/agentchat_openlit.ipynb)
> 
> Also seeing: `agentchat_openlit.ipynb: front matter missing from notebook metadata` in the pipeline output as well.
> 
> Did you follow [Contributing](https://github.com/ag2ai/ag2/blob/9baabc4bda30de0d19f62c86bd6d489821319dd3/notebook/contributing.md#L4)?
> 
> I pulled your changes locally and was able to get it to build... @patcher9

@patcher9 please go through this once to fix the checks. Thanks

**Pull request closed without merging**
