### PR TITLE
dev model agnostic structured output

### PR DESCRIPTION
**Pull request by ohdearquant**
## Related issue number

See #23 and please feel free to discuss the feature in there and the code development in here.

## Checks

- [ ] I've included any doc changes needed for https://ag2ai.github.io/autogen/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Hk669** [comment]
Hey @ohdearquant you can check on the new issue #23, feel free to propose new changes. Thanks

cc @marklysze

**Comment by qingyun-wu** [comment]
@ohdearquant let's work out a plan here. I would encourage to start from smaller PRs. Thank you!

**Comment by ohdearquant** [comment]
ok, @qingyun-wu  should we close this one for now then? I can make smaller PRs in future. Above requires a lot of architecture changes, maybe not the right move.

**Comment by ohdearquant** [comment]
@qingyun-wu @marklysze @davorrunje thoughts on making message into objects? 

### Why Object-Based Messages?
1. Enables more flexible operations on messages
2. Improves configuration and parameter management
3. Creates synergy with structured output patterns

### Implementation Strategy
We could pursue a hybrid approach that balances structure and flexibility. For example, for structured output content formatting (per @marklysze's recent point), adding a custom `format()` to the Pydantic model is low overhead, @sternakt.

However, requiring specialized handling for every structured output can burden users. Not every output needs custom formatting, but conversation context benefits from flexible structure. 

One potential solution: maintain the Pydantic structure while adding optional uniform formatting capabilities alongside the `format()` function.

**Pull request closed without merging**
