### PR TITLE
[Autobuild] Introducing Captain Agent

### PR DESCRIPTION
**Pull request by LeoLjl**
This PR introduces CaptainAgent.

CaptainAgent is an agent that can break down tasks and dynamically call AutoBuild as a tool to solve the subtasks. In one tool call, the CaptainAgent will provide the building task, execution task and group name. The building task is used to assemble group of experts, the execution task is what the experts need to solve.

We propose a RAG-like pipeline for expert group generation. Given a building task, we perform similarity search in agent library and find topk candidates, then let LLM to select the best fit. If no expert is suitable for the task, new experts will be generated. Tools will be retrieved and binded to the experts.

Below is the roadmap for merging it.

- [x] Add full content of tool library.
- [x] Add test for captain agent.
- [x] Revise the notebook that introduces MetaAgent. The current one only involves tool library.
- [x] Finish blog post.

## Checks

- [x] I've included any doc changes needed for https://ag2ai.github.io/ag2
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by Hk669 — COMMENTED** [review]
i just wanted to clarify, why are we using seperate py file for every math function. @LeoLjl 
Thanks!

**Comment by sonichi** [comment]
@LeoLjl could you please check the failing docs/checks CI? @qingyun-wu could you please set up the openai CI?

**Review by sonichi — COMMENTED** [review]
My suggestion of breaking down the PRs:
1. doc + blogpost + test. Out-of-the-box usage of CaptainAgent. Shortest code example. No customization.
2. Working code for the documented functionality in (1) which passes the test.
3. Add configurable options in doc + blogpost + test.
4. Working code for the documented functionality in (3) which passes the test.

We can keep this PR as a draft for having an overall understanding. Then create new PRs following (1)-(4). (1) and (2) are minimal requirements for initial release. We'll need focused discussion for each PR, and each PR will depend on previous ones.

What do you think?

**Comment by LeoLjl** [comment]
> My suggestion of breaking down the PRs:
> 
> 1. doc + blogpost + test. Out-of-the-box usage of CaptainAgent. Shortest code example. No customization.
> 2. Working code for the documented functionality in (1) which passes the test.
> 3. Add configurable options in doc + blogpost + test.
> 4. Working code for the documented functionality in (3) which passes the test.
> 
> We can keep this PR as a draft for having an overall understanding. Then create new PRs following (1)-(4). (1) and (2) are minimal requirements for initial release. We'll need focused discussion for each PR, and each PR will depend on previous ones.
> 
> What do you think?

Of course. However, I am not sure if we can get it delivered on time given the tight scedule if we break it down and merge separately.

**Comment by qingyun-wu** [comment]
@LeoLjl for the interface, let's just do sth like this

```python
captain_agent = CaptainAgent(
    name="captain_agent",
    llm_config=llm_config,
    agent_lib="xxxx",
    tool_lib="xxxx",
    code_execution_config={"use_docker": False, "work_dir": "groupchat"},
)
```

**Pull request closed without merging**
