### PR TITLE
Adding AnthropicVertexAI API support in the Anthropic LLM lib under oai

### LINKED ISSUE #308: [Feature Request]: AnthropicVertexAI API support in the Anthropic LLM support
### Is your feature request related to a problem? Please describe.

I am using Anthropic Haiku for my Agents, which is run via VertexAI. This is a convenient method for us, as we have decent GCP credits for development because of startup programs.method is convenient 

### Describe the solution you'd like

Adding AnthropicVertex API support in oai/anthropic.py.

I will raise a PR for this support, will wait for approval and release

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shriyanshagnihotri**
## Why are these changes needed?

The changes include adding support AnthropicVertex inside oai/anthropic.py and oai/client.py, so that Anthropic models running in GCP can be used in Ag2 for building Agents.

## Related issue number

Closes #308 

## Checks

- [X] I've included any doc changes needed for https://docs.ag2.ai/. See https://docs.ag2.ai/docs/contributor-guide/documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [  ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by marklysze** [comment]
Hey @shriyanshagnihotri, thanks for putting this PR together.

I have tested it without GCP and with GCP and it works well!

It's currently not passing the pre-commit tests because it's missing a blank line as the last line in the both the `anthropic.py` and `test_anthropic.py` files, can you please add them in?

Also, are you on discord, would you be able to message me your email address so we can send through a CLA (Contributor License Agreement) for your contribution? My Discord is `msze_`.

**Comment by marklysze** [comment]
Can I also ask if you could add instructions to the documentation page for Anthropic:
/website/docs/topics/non-openai-models/cloud-anthropic.ipynb

It will be useful for others looking to do the same.

**Comment by marklysze** [comment]
> @marklysze please check, I have updated the documentation as well. Also regarding the extra enter, I have added, but it seems the pre-commit is removing it. please check

Thanks @shriyanshagnihotri, if you're able to give me access to the repository I can edit it.

**Comment by shriyanshagnihotri** [comment]
@marklysze : Done I have added you as a writer to https://github.com/test-zeus-ai/ag2

**Comment by marklysze** [comment]
Thanks @shriyanshagnihotri, I've just tweaked the notebook text a bit to format the bullet points. All passed the pre-commit so I think we're good to go :)

**Review by marklysze — APPROVED** [review]

**Pull request merged**
